---

#
# Install nginx and configure for Laravel/LEMP stack
#

- name: "Install Nginx"
  apt: name=nginx state=latest

- name: "Install Certbot"
  become: true
  apt_repository:
    repo: 'ppa:certbot/certbot'

- name: "Install Certbot's Nginx Package"
  apt: name=python-certbot-nginx state=present

# can run sudo certbot --nginx -d example.com -d www.example.com after these installations

- name: "Start nginx service"
  service:
      name: nginx
      state: started
  become: yes

- name: "Copy the nginx config file and restart nginx"
  copy:
      src: ./laravel-nginx.cfg
      dest: /etc/nginx/sites-available/default

- name: "Create symlink between sites-enabled and sites-available"
  file:
      src: /etc/nginx/sites-available/default
      dest: /etc/nginx/sites-enabled/default
      state: link
  become: yes

- name: "Restart nginx service"
  service:
      name: nginx
      state: restarted
  become: yes
