---

- name: Get name of what will soon be the old deployment directory
  shell: sudo cat /home/ubuntu/current_deployment.txt
  register: previous_deployment

- name: Create a unique ID
  shell: echo "`date +"%Y%m%d%H%M%S"`-$(cat /dev/urandom | tr -cd [:alpha:] | tr '[:upper:]' '[:lower:]' | head -c 4)"
  register: unique_id

- name: Make current_deployment.txt
  raw: echo joechem_{{ unique_id.stdout }} > /home/ubuntu/current_deployment.txt

- name: Clone from remote master branch into newly made directory
  raw: sudo git clone https://github.com/jdelnano/joechem.git joechem_{{ unique_id.stdout }}

- name: Copy .env file into newly made directory
  raw: cp /home/ubuntu/.env /home/ubuntu/joechem_{{ unique_id.stdout }}

- name: Change ownership back to ubuntu and www-data
  raw: sudo chown -R ubuntu:www-data /home/ubuntu/joechem_{{ unique_id.stdout }}

- name: Permissions command f
  raw: sudo find /home/ubuntu/joechem_{{ unique_id.stdout }} -type f -exec chmod 664 {} \;

- name: Permissions command d
  raw: sudo find /home/ubuntu/joechem_{{ unique_id.stdout }} -type d -exec chmod 775 {} \;

- name: Change to new joechem directory
  raw: cd /home/ubuntu/joechem_{{ unique_id.stdout }}

- name: Change group of cache file
  raw: sudo chgrp -R www-data  /home/ubuntu/joechem_{{ unique_id.stdout }}/storage/ /home/ubuntu/joechem_{{ unique_id.stdout }}/bootstrap/cache/

- name: Change group of cache file
  raw: sudo chmod -R ug+rwx  /home/ubuntu/joechem_{{ unique_id.stdout }}/storage/ /home/ubuntu/joechem_{{ unique_id.stdout }}/bootstrap/cache/

- composer:
    command: install
    working_dir: /home/ubuntu/joechem_{{ unique_id.stdout }}

- name: Change ownership back to ubuntu and www-data
  raw: sudo chown -R ubuntu:www-data /home/ubuntu/joechem_{{ unique_id.stdout }}

- name: Rerun migrations 
  raw: php /home/ubuntu/joechem_{{ unique_id.stdout }}/artisan migrate --force
  
- name: Run Laravel optimization commands
  raw: php /home/ubuntu/joechem_{{ unique_id.stdout }}/artisan optimize

- name: Run Laravel optimization commands
  raw: php /home/ubuntu/joechem_{{ unique_id.stdout }}/artisan cache:clear

- name: Run Laravel optimization commands
  raw: php /home/ubuntu/joechem_{{ unique_id.stdout }}/artisan view:clear

- name: Run Laravel optimization commands
  raw: php /home/ubuntu/joechem_{{ unique_id.stdout }}/artisan config:clear

- name: Force establish new symlink
  raw: sudo ln -sfn /home/ubuntu/joechem_{{ unique_id.stdout }}/* /var/www/joechem

- name: Change ownership to ubuntu and www-data
  raw: sudo chown -R ubuntu:www-data /var/www/

- name: Restart nginx
  service:
      name: nginx
      state: restarted

- name: Restart php-fpm
  service:
      name: php7.1-fpm
      state: restarted

- name: Delete now completely outdated deployment
  raw: sudo rm -rf /home/ubuntu/{{ previous_deployment.stdout }}
