---

#
# Install php and other libraries/dependencies for Laravel
#

- name: "Add PHP 7 PPA repository"
  become: true
  apt_repository:
    repo: 'ppa:ondrej/php'

- name: "Install Other Packages/Libraries"
  with_items: "{{ ubuntu_laravel_deps }}"
  apt: name={{ item.deps }} state=present

- name: "Install PHP"
  with_items: "{{ php_laravel_deps }}"
  apt: name={{ item.deps }} state=present
